/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Database {
  /**
   * Begin a write transaction. Must `.commit()` or `.rollback()`.
   * Dropping without either rolls back.
   */
  transaction(): Transaction
  /** SELECT returns `Array<Object>` (each row is a plain object). */
  query(sql: string, params?: Array<JsonValue> | undefined | null): Array<Record<string, any>>
  /**
   * Filesystem watcher on the .db-wal file. `await ev.next()` resolves
   * on every commit to the database (any process, any writer).
   *
   * N subscribers share a single background poll thread via the
   * core SharedWalWatcher.
   */
  walEvents(): WalEvents
  /**
   * Delete notifications older than a duration, or beyond a count.
   * Returns number of rows removed.
   */
  pruneNotifications(olderThanS?: number | undefined | null, maxKeep?: number | undefined | null): number
}

export declare class Transaction {
  execute(sql: string, params?: Array<JsonValue> | undefined | null): number
  query(sql: string, params?: Array<JsonValue> | undefined | null): Array<Record<string, any>>
  /**
   * Publish a cross-process notification. `payload` is any
   * JSON-serializable value; it's `JSON.stringify`'d on the way in
   * and `JSON.parse`'d by consumers on the way out. Matches the
   * Python binding's unconditional `json.dumps` contract so payloads
   * round-trip identically across bindings.
   */
  notify(channel: string, payload: JsonValue): number
  commit(): void
  rollback(): void
}

export declare class WalEvents {
  /** Await the next WAL change. Resolves on every DB commit. */
  next(): Promise<void>
  /** Stop this subscription eagerly. Idempotent. */
  close(): void
}

export declare function open(path: string, maxReaders?: number | undefined | null): Database
